<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" >

<title>Promise简介 | Blog-wmxie</title>

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<link rel="shortcut icon" href="https://xiewangmei.github.io/favicon.ico?v=1606802819660">
<link rel="stylesheet" href="https://xiewangmei.github.io/styles/main.css">



<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>



    <meta name="description" content="所谓Promise，简单来说就是一个容器，里面保存着未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise是一个对象，从它可以获取异步操作的消息，例如请求成功后返回的数据，请求失败后的错误信息等。Promise提供统一的..." />
    <meta name="keywords" content="xyqiu" />
  </head>
  <body>
    <div id="app" class="main">

      <div class="sidebar" :class="{ 'full-height': menuVisible }">
  <div class="top-container" data-aos="fade-right">
    <div class="top-header-container">
      <a class="site-title-container" href="https://xiewangmei.github.io">
        <img src="https://xiewangmei.github.io/images/avatar.png?v=1606802819660" class="site-logo">
        <h1 class="site-title">Blog-wmxie</h1>
      </a>
      <div class="menu-btn" @click="menuVisible = !menuVisible">
        <div class="line"></div>
      </div>
    </div>
    <div>
      
        
          <a href="/" class="site-nav">
            首页
          </a>
        
      
        
          <a href="https://xiewangmei.github.io/archives" class="site-nav">
            归档
          </a>
        
      
        
          <a href="/tags" class="site-nav">
            标签
          </a>
        
      
        
          <a href="/post/about" class="site-nav">
            关于
          </a>
        
      
    </div>
  </div>
  <div class="bottom-container" data-aos="flip-up" data-aos-offset="0">
    <div class="social-container">
      
        
      
        
      
        
      
        
      
        
      
    </div>
    <div class="site-description">
      念念不忘，必有回响~
    </div>
    <div class="site-footer">
      Powered by <a href="https://github.com/getgridea/gridea" target="_blank">Gridea</a> | <a class="rss" href="https://xiewangmei.github.io/atom.xml" target="_blank">RSS</a>
    </div>
  </div>
</div>


      <div class="main-container">
        <div class="content-container" data-aos="fade-up">
          <div class="post-detail">
            <h2 class="post-title">Promise简介</h2>
            <div class="post-date">2020-10-15</div>
            
            <div class="post-content" v-pre>
              <p>所谓Promise，简单来说就是一个容器，里面保存着未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise是一个对象，从它可以获取异步操作的消息，例如请求成功后返回的数据，请求失败后的错误信息等。Promise提供统一的API，各种异步操作都可以用同样的方式进行处理。</p>
<h2 id="promise的特点">Promise的特点</h2>
<ul>
<li>对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：<code>pending</code>、<code>fulfilled</code>和<code>rejected</code>。只有异步操作的结果可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是Promise（承诺）这个名字的由来，表示其他手段无法改变。</li>
<li>一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：<code>pending → fulfilled</code>和<code>pending → rejected</code>。一旦状态发生改变，就会一直保持其终态不再改变。如果改变已经发生，再对Promise添加回调函数，也会立即得到这个结果。这与事件不同，事件一旦错过了，再去监听，是得不到结果的。</li>
</ul>
<p>下面是一个状态转变的例子：</p>
<figure data-type="image" tabindex="1"><img src="https://xiewangmei.github.io/post-images/1602727622438.png" alt="状态转变" loading="lazy"></figure>
<p>有了Promise对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。此外，Promise对象提供统一的接口，使得控制异步操作更加容易。<br>
Promise也有一些缺点。首先，无法取消Promise，<strong>一旦新建它就会立即执行</strong>，无法中途取消。其次，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。第三，当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。</p>
<h2 id="promise的基本用法">Promise的基本用法</h2>
<h3 id="语法">语法</h3>
<pre><code class="language-javascript">new Promise( function(resolve, reject) {...} /* executor */  );
</code></pre>
<p><code>Promise</code>构造函数接受一个函数作为参数，该函数的两个参数分别是<code>resolve</code>和<code>reject</code>。它们是两个函数，由 JavaScript 引擎提供，不用自己部署。</p>
<p><code>resolve</code>函数的作用是，将<code>Promise</code>对象的状态从“未完成”变为“成功”（即从 pending 变为 fulfilled），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；<code>reject</code>函数的作用是，将<code>Promise</code>对象的状态从“未完成”变为“失败”（即从 pending 变为 rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。</p>
<p><code>Promise</code>实例生成以后，可以用<code>then</code>方法分别指定<code>resolved</code>状态和<code>rejected</code>状态的回调函数。</p>
<pre><code class="language-jsx">promise.then(function(value) {
  // success
}, function(error) {
  // failure
});
</code></pre>
<p><code>then</code>方法可以接受两个回调函数作为参数。第一个回调函数是<code>Promise</code>对象的状态变为<code>resolved</code>时调用，第二个回调函数是<code>Promise</code>对象的状态变为<code>rejected</code>时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接受<code>Promise</code>对象传出的值作为参数。</p>
<p><strong>注意，下面两种方式是等价的：</strong></p>
<pre><code class="language-jsx">promise.then(null, function(error) {
  // failure
});
promise.catch(function(error) {
  // failure
});
</code></pre>
<h3 id="实例">实例</h3>
<h4 id="异步加载图片">异步加载图片</h4>
<pre><code class="language-jsx">const loadImageAsync = url =&gt; {
    return new Promise((resolve, reject) =&gt; {
        const image = new Image();
        // 加载成功, resolve
        image.onload = () =&gt; resolve(image);
        // 加载失败, reject
        image.onerror = () =&gt; reject(new Error(&quot;Image load failed at &quot; + url));
        image.src = url;
    });  
};
</code></pre>
<h4 id="实现一个简单ajax">实现一个简单Ajax</h4>
<pre><code class="language-jsx">const Ajax = function(url) {
  return new Promise(function(resolve, reject) {
    const onReadyStateChange = function() {
      if (this.readyState !== 4) return;
      if (this.status === 200) {
        resolve(this.response);
      } else {
        reject(new Error(this.statusText));
      }
    };
    const client = new XMLHttpRequest();
    client.open(&quot;GET&quot;, url);
    client.onreadystatechange = onReadyStateChange;
    client.responseType = &quot;json&quot;;
    client.setRequestHeader(&quot;Accept&quot;, &quot;application/json&quot;);
    client.send();
  });
};
</code></pre>
<p>上述代码对原生<code>XMLHttpRequest</code>对象做了一次封装，用于发送一个Get请求，并且返回一个<code>Promise</code>对象。在<code>onReadyStateChange</code>函数体中，根据请求状态分别调用<code>resolve</code>和<code>reject</code>并传入对应的返回数据或错误信息，这时候如果通过<code>then</code>添加回调函数，那么<code>resolve</code>和<code>reject</code>的参数会被传递给各自对应的回调函数<code>onFulfilled</code>和<code>onRejected</code>。</p>
<p>使用：</p>
<pre><code class="language-jsx">// Node在8888端口起一个node服务
Ajax(&quot;http://localhost:8888/user/list&quot;).then(
    json =&gt; console.log(json),
    error =&gt; console.log(error)
);
</code></pre>
<p>效果：</p>
<figure data-type="image" tabindex="2"><img src="https://xiewangmei.github.io/post-images/1602727648090.png" alt="Ajax" loading="lazy"></figure>
<h4 id="resolve参数是promise">Resolve参数是Promise</h4>
<p><code>resolve</code>函数的参数除了正常值外，还可能是另一个<code>Promise</code>对象：</p>
<pre><code class="language-jsx">const p1 = new Promise(function (resolve, reject) {
  // ...
});

const p2 = new Promise(function (resolve, reject) {
  // ...
  resolve(p1);
})
</code></pre>
<p>上面代码中，<code>p1</code>和<code>p2</code>都是 Promise 的实例，但是<code>p2</code>的<code>resolve</code>方法将<code>p1</code>作为参数，即一个异步操作的结果是返回另一个异步操作。</p>
<p>注意，这时<code>p1</code>的状态就会传递给<code>p2</code>，也就是说，<code>p1</code>的状态决定了<code>p2</code>的状态。<strong>如果<code>p1</code>的状态是<code>pending</code>，那么<code>p2</code>的回调函数就会等待<code>p1</code>的状态改变</strong>；如果<code>p1</code>的状态已经是<code>resolved</code>或者<code>rejected</code>，那么<code>p2</code>的回调函数将会立刻执行。</p>
<pre><code class="language-jsx">const p1 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; reject(new Error('fail')), 3000);
});
const p2 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; resolve(p1), 1000);
});
p2.then(console.log).catch(console.log);
</code></pre>
<p>上面代码中，<code>p1</code>是一个 Promise，3 秒之后变为<code>rejected</code>。<code>p2</code>的状态本该在 1 秒时改变，但由于<code>resolve</code>方法接收的参数是<code>p1</code>，而在 1 秒这个时机，<code>p1</code>的状态还是<code>pending</code>，所以会等待<code>p1</code>的状态改变，此时<code>p2</code>自己的状态无效，由<code>p1</code>的状态决定，并且<code>p2</code>的<code>then</code>语句都变成针对<code>p1</code>。再经过 2 秒，<code>p1</code>变为<code>rejected</code>，触发<code>catch</code>方法指定的回调函数。</p>
<p>思考下面这三种情形，是什么结果？</p>
<pre><code class="language-jsx">// 情形一
const p1 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; reject(new Error('fail')), 3000);
});
const p2 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; resolve(p1), 10000);// 时间改为10S
});
p2.then(console.log).catch(console.log);

// 情形二
const p1 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; reject(new Error('fail')), 3000);
}).catch(console.log);
const p2 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; resolve(p1), 10000);// 时间改为10S
});
p2.then(console.log).catch(console.log);

// 情形三
const p1 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; reject(new Error('fail')), 3000);
});
p1.catch(console.log);
const p2 = new Promise(function (resolve, reject) {
  setTimeout(() =&gt; resolve(p1), 10000);// 时间改为10S
});
p2.then(console.log).catch(console.log);
</code></pre>
<h4 id="executor函数执行特点">Executor函数执行特点</h4>
<pre><code class="language-jsx">const p = new Promise((resolve, reject) =&gt; {
  resolve(1);
  console.log(2);
}).then(console.log);
console.log(3);
// 2
// 3
// 1
</code></pre>
<p><code>Promise</code>对象在创建时，<code>executor</code>函数会<strong>立即执行</strong>，又因为<code>resolve</code>或者<code>reject</code>并<strong>不会终止</strong><code>executor</code>函数的执行，所以2最先输出；<code>then</code>方法是异步的，所以不用等到<code>then</code>方法的输出，直接会执行同步代码<code>console.log(3)</code>，最后才会执行<code>then</code>中的回调，输出<code>resolve</code>的参数。</p>
<p>一般来讲，调用<code>resolve</code>或者<code>reject</code>后，<code>Promise</code>状态发生改变，使命就算完成，后续操作应该放到<code>then</code>方法中，而不应该在写在<code>executor</code>函数中的<code>resolve</code>和<code>reject</code>之后。</p>
<h4 id="promiseprototypethen">Promise.prototype.then()</h4>
<p><code>Promise</code>实例具有<code>then</code>方法，它的作用是给<code>Promise</code>实例添加状态改变时的回调函数。<code>then</code>方法参数是可选的，共有两个参数<code>onFulfilled</code>和<code>onRejected</code>，分别对应<code>pending → fulfilled</code>和<code>pending → rejected</code>两种状态变化的回调。</p>
<p><code>then</code>方法返回的是一个新的<code>Promise</code>实例（注意，不是原来的那个<code>Promise</code>实例），这也是<code>Promise</code>支持链式写法的原因。</p>
<pre><code class="language-jsx">const promise1 = new Promise((resolve, reject) =&gt; resolve([&quot;kzhang&quot;, &quot;xiaozhang&quot;]));
const promise2 = promise1.then(console.log);// [&quot;kzhang&quot;, &quot;xiaozhang&quot;]
console.log(promise1 === promise2);// false

// 链式调用
const promise3 = promise1.then(users =&gt; users[0]).then(console.log);// kzhang
</code></pre>
<p>采用链式的<code>then</code>，可以指定一组按照次序调用的回调函数。这时，前一个回调函数，有可能返回的还是一个<code>Promise</code>对象（即有异步操作），这时后一个回调函数，就会等待该<code>Promise</code>对象的状态发生变化，才会被调用。</p>
<pre><code class="language-jsx">const promiseA = Promise.resolve();
const promiseB = promiseA.then(() =&gt; Ajax(&quot;combo/options/list&quot;));
const promiseC = promiseB.then(comboList =&gt; Ajax(`config/${comboList[0]}`));
const promiseD = promiseC.then(console.log);
// 等价于:
Promise.resolve()
    .then(() =&gt; Ajax(&quot;combo/options/list&quot;))
    .then(comboList =&gt; Ajax(`config/${comboList[0]}`))
    .then(console.log);
</code></pre>
<p>上面代码中，第一个<code>then</code>指定的回调函数是发送一个<code>Ajax</code>请求，第二个<code>then</code>会等待该请求完成后，拿取第一条数据继续发送第二个请求，最后一个<code>then</code>则等待第二个请求完成后，直接打印结果。</p>
<h4 id="promiseprototypecatch">Promise.prototype.catch()</h4>
<p><code>Promise.prototype.catch</code>方法是<code>.then(null, rejection)</code>的别名，用于指定发生错误时的回调函数。</p>
<pre><code class="language-jsx">Ajax(&quot;user/list&quot;).then(users =&gt; loadUserTable(users)).catch(err =&gt; {
  console.log(&quot;醒醒, 你的代码报错了&quot;, err);
});
</code></pre>
<p>上面代码中，发送一个请求获取用户列表，如果请求正常返回，执行<code>then</code>方法指定的回调来加载表格数据，否则执行<code>catch</code>方法指定的回调来打印错误信息。另外，如果<code>then</code>方法指定的回调在运行中抛出错误，也会被<code>catch</code>方法捕获。</p>
<pre><code class="language-jsx">const promise = new Promise((resolve, reject) =&gt; {throw new Error(&quot;报错啦&quot;);});
promise.catch(console.log);// Error: 报错啦
</code></pre>
<p>上面代码中，<code>Promise</code>内部抛出一个错误，就被<code>catch</code>方法指定的回调函数捕获，这种写法和下面两种写法等价：</p>
<pre><code class="language-jsx">// 写法一
const promise = new Promise((resolve, reject) =&gt; {
  try {
    throw new Error(&quot;报错啦&quot;);
  } catch(e) {
    reject(e);
  }
});
promise.catch(console.log);

// 写法二
const promise = new Promise((resolve, reject) =&gt; {
  reject(new Error(&quot;报错啦&quot;));
});
promise.catch(console.log);
</code></pre>
<p>如果<code>Promise</code>的状态已经变成<code>fulfilled</code>，再抛出错误则是无效的，这是因为<code>Promise</code>状态一旦发生改变后，就会一直保持该终态，例如：</p>
<pre><code class="language-jsx">const promise = new Promise((resolve, reject) =&gt; { 
  resolve(&quot;fulfilled&quot;);
  throw new Error(&quot;报错啦&quot;);
});
promise.then(console.log).catch(console.log);
// fulfilled
</code></pre>
<p><code>Promise</code>的错误具有“冒泡”性质，会一直向后传递，知道被捕获为止。也就是说，错误总是会被下一个<code>catch</code>语句捕获。例如，<code>promise.then(...).then(...).catch(...)</code>，两个<code>then</code>中任意一个发生错误，都会被最后的<code>catch</code>捕获。</p>
<p>一般来说，用<code>catch</code>来指定<code>rejected</code>状态的回调要优于用<code>then(null, onRejected)</code>的方式，因为<code>catch</code>方式能捕获前面的<code>then</code>方法执行中的错误，也更接近于同步的写法（<code>try/catch</code>）。</p>
<p><code>catch</code>方法返回的还是一个<code>Promise</code>对象，因此后面还是可以接着调用<code>then</code>方法：</p>
<pre><code class="language-jsx">const promise1 = new Promise((resolve, reject) =&gt; reject(new Error(&quot;报错啦&quot;)));
const promise2 = promise1.catch(err =&gt; {
  console.log(err);
  return &quot;错误catch住, 并处理完成&quot;
});
promise2.then(console.log);
</code></pre>
<p>上面代码中，<code>promise1</code>变为<code>rejected</code>态，调用<code>catch</code>回调，并返回一段文本，供<code>promise2</code>的<code>then</code>回调打印。若<code>promise1</code>没有报错，则会跳过<code>catch</code>。</p>
<pre><code class="language-jsx">Promise.resolve().catch(console.log).then(() =&gt; console.log('carry on'));
</code></pre>
<p>上面这段代码，由于没有报错，所以会跳过<code>catch</code>直接执行<code>then</code>。</p>
<h4 id="promiseprototypefinally">Promise.prototype.finally()</h4>
<p><code>finally</code>方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。</p>
<pre><code class="language-jsx">Ajax(&quot;http://localhost:8888/user/list&quot;)
  .then(users =&gt; {
    loadUserTable(users);
    setMask(false);
   })
  .catch(err =&gt; {
    console.log(err);
    setMask(false);  
  });
</code></pre>
<p>上面这段代码，不管请求是否成功，在结束后都会调用<code>setMask(false)</code>操作来去除遮罩。显然，<code>setMask(false)</code>是一个必然执行的操作，可以放到<code>finally</code>中：</p>
<pre><code class="language-jsx">Ajax(&quot;http://localhost:8888/user/list&quot;)
  .then(loadUserTable)
  .catch(console.log)
  .finally(() =&gt; setMask(false));
</code></pre>
<p><code>finally</code>方法的回调函数不接受任何参数，这意味着没有办法知道，前面的<code>Promise</code>状态到底是<code>fulfilled</code>还是<code>rejected</code>。这表明，<code>finally</code>方法里面的操作，应该是与状态无关的，不依赖于<code>Promise</code>的执行结果。</p>
<h4 id="promiseall">Promise.all()</h4>
<p><code>Promise.all</code>方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。</p>
<pre><code class="language-jsx">const p = Promise.all([p1, p2, p3]);
</code></pre>
<p>上面代码中，<code>Promise.all</code>方法接受一个数组作为参数，<code>p1</code>、<code>p2</code>、<code>p3</code>都是<code>Promise</code>实例，如果不是，就会先调用下面讲到的<code>Promise.resolve</code>方法，将参数转为<code>Promise</code>实例，再进一步处理。</p>
<p><code>p</code>的状态由<code>p1</code>、<code>p2</code>、<code>p3</code>决定，分成两种情况：</p>
<ul>
<li>只有<code>p1</code>、<code>p2</code>、<code>p3</code>的状态都变成<code>fulfilled</code>，<code>p</code>的状态才会变成<code>fulfilled</code>，此时<code>p1</code>、<code>p2</code>、<code>p3</code>的返回值组成一个数组，传递给<code>p</code>的回调函数。</li>
<li>只要<code>p1</code>、<code>p2</code>、<code>p3</code>之中有一个被<code>rejected</code>，<code>p</code>的状态就变成<code>rejected</code>，此时第一个被<code>reject</code>的实例的返回值，会传递给<code>p</code>的回调函数。</li>
</ul>
<pre><code class="language-jsx">// 连接数据库
const databasePromise = connectDatabase();
// 查询所有书籍
const booksPromise = databasePromise.then(findAllBooks);
// 查询当前登录用户
const userPromise = databasePromise.then(getCurrentUser);
// 返回针对该用户的推荐书籍
Promise.all([booksPromise, userPromise]).then(
    ([books, user]) =&gt; pickTopRecommentations(books, user)
);
</code></pre>
<p>上面代码中，<code>booksPromise</code>和<code>userPromise</code>是两个异步操作，只有等到它们的结果都返回了，才会触发<code>pickTopRecommentations</code>这个回调函数。</p>
<pre><code class="language-jsx">const p1 = new Promise((resolve, reject) =&gt; resolve('hello'))
             .then(result =&gt; result)
             .catch(e =&gt; e);
const p2 = new Promise((resolve, reject) =&gt; { throw new Error('报错了'); })
             .then(result =&gt; result)
             .catch(e =&gt; e);
Promise.all([p1, p2])
    .then(result =&gt; console.log(result))// [&quot;hello&quot;, Error: 报错了]
    .catch(e =&gt; console.log(e));
</code></pre>
<p>上面这段代码，并没有在最后一行的<code>catch</code>中打印结果，这是因为<code>p2</code>对象指定了<code>catch</code>回调，而<code>catch</code>返回的又是一个正常的<code>Promise</code>对象，所以<code>Promise.all</code>接收了两个<code>fulfilled</code>状态的<code>Promise</code>，自然就触发<code>Promise.all</code>的<code>then</code>方法。</p>
<p>改写一下，去掉<code>p2</code>的<code>catch</code>回调，则可以触发<code>Promise.all</code>的<code>catch</code>回调：</p>
<pre><code class="language-jsx">const p1 = new Promise((resolve, reject) =&gt; resolve('hello')).then(result =&gt; result);
const p2 = new Promise((resolve, reject) =&gt; { throw new Error('报错了');})
             .then(result =&gt; result);
Promise.all([p1, p2])
    .then(result =&gt; console.log(result))
    .catch(e =&gt; console.log(e));// Error: 报错了
</code></pre>
<h4 id="promiserace">Promise.race()</h4>
<p><code>Promise.race</code>方法同样是将多个 Promise 实例，包装成一个新的 Promise 实例。</p>
<pre><code class="language-jsx">const p = Promise.race([p1, p2, p3]);
</code></pre>
<p>上面代码中，只要<code>p1</code>、<code>p2</code>、<code>p3</code>之中有一个实例率先改变状态，<code>p</code>的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给<code>p</code>的回调函数。</p>
<p><code>Promise.race</code>方法的参数与<code>Promise.all</code>方法一样，如果不是 Promise 实例，就会先调用下面讲到的<code>Promise.resolve</code>方法，将参数转为 Promise 实例，再进一步处理。</p>
<pre><code class="language-jsx">const p = Promise.race([
  Ajax(&quot;/long-time-request&quot;),// 耗时请求
  new Promise((resolve, reject) =&gt; {
    setTimeout(() =&gt; reject(new Error('request timeout')), 5000);
  })
]);
p.then(console.log).catch(console.error);
</code></pre>
<p>上面代码中，如果 5 秒之内<code>fetch</code>方法无法返回结果，变量<code>p</code>的状态就会变为<code>rejected</code>，从而触发<code>catch</code>方法指定的回调函数。</p>
<h4 id="promiseresolve">Promise.resolve()</h4>
<p><code>Promise.resolve(value)</code>方法返回一个根据<code>value</code>解析后的<code>Promise</code>对象。</p>
<p>有以下几种情况：</p>
<ul>
<li>
<p>如果<code>value</code>为<code>promise</code>，返回这个<code>promise</code></p>
<pre><code class="language-jsx">const p1 = Promise.resolve(&quot;xyqiu&quot;);
const p2 = Promise.resolve(p1);
console.log(p1 === p2);// true
p2.then(value =&gt; console.log(value));// 'xyqiu'
</code></pre>
</li>
<li>
<p>如果<code>value</code>是<code>thenable</code>对象（即带有<code>then</code>方法），返回的<code>promise</code>会“跟随”这个<code>thenable</code>对象，采用它的最终状态</p>
<pre><code class="language-jsx">const p1 = Promise.resolve({ then: (resolve, reject) =&gt; resolve(&quot;xyqiu&quot;) });
const p2 = Promise.resolve({ then: (resolve, reject) =&gt; reject(&quot;Error&quot;) });
p1.then(console.log);// 'xyqiu'
p2.catch(console.log);// 'Error'
</code></pre>
</li>
<li>
<p>如果<code>value</code>不是<code>thenable</code>对象，返回的<code>promise</code>将以此值完成</p>
<pre><code class="language-jsx">const p1 = Promise.resolve(&quot;xyqiu1&quot;);
const p2 = Promise.resolve({ name: &quot;xyqiu2&quot; });
p1.then(console.log);// 'xyqiu1'
p2.then(console.log);// { name: &quot;xyqiu2&quot; }
</code></pre>
</li>
</ul>
<h4 id="promisereject">Promise.reject()</h4>
<p><code>Promise.reject(reason)</code>方法也会返回一个新的<code>Promise</code>实例，该实例的状态为<code>rejected</code>。</p>
<pre><code class="language-jsx">// 下面两种方式等价
const p1 = Promise.reject(&quot;报错了&quot;);
const p2 = new Promise((resolve, reject) =&gt; reject(&quot;报错了&quot;));
</code></pre>
<p><code>Promise.reject()</code>方法的参数，会<strong>原封不动</strong>地作为<code>reject</code>的理由，变为后续方法的参数。这一点与<code>Promise.resolve()</code>方法不一致。</p>
<pre><code class="language-jsx">const thenable = { then: (resolve, reject) =&gt; reject('报错了') };
Promise.reject(thenable).catch(e =&gt; console.log(e === thenable));// true
</code></pre>

            </div>
            
              <div class="tag-container">
                
                  <a href="https://xiewangmei.github.io/tag/xyqiu/" class="tag">
                    xyqiu
                  </a>
                
              </div>
            
            
              <div class="next-post">
                <div class="next">下一篇</div>
                <a href="https://xiewangmei.github.io/post/learn-regexp/">
                  <h3 class="post-title">
                    学会写正则
                  </h3>
                </a>
              </div>
            

            

          </div>

        </div>
      </div>
    </div>

    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script type="application/javascript">

AOS.init();

var app = new Vue({
  el: '#app',
  data: {
    menuVisible: false,
  },
})

</script>






  </body>
</html>
